# Homebrew tools are initialized in ~/.zprofile.

# Node version management.
if command -v brew >/dev/null 2>&1; then
  FNM_PATH="$(brew --prefix fnm 2>/dev/null)/bin"
  if [[ -d "$FNM_PATH" ]]; then
    eval "$(fnm env --shell zsh)"
  fi
fi

# Juliaup, when installed.
if [[ -d "$HOME/.juliaup/bin" ]]; then
  path=("$HOME/.juliaup/bin" $path)
  export PATH
fi
[[ -f "$HOME/.julia/juliaup/completions/zsh.zsh" ]] && \
  source "$HOME/.julia/juliaup/completions/zsh.zsh"

# Oh My Zsh and shell quality-of-life plugins.
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""
plugins=(git macos colored-man-pages command-not-found extract sudo)
[[ -f "$ZSH/oh-my-zsh.sh" ]] && source "$ZSH/oh-my-zsh.sh"

for plugin in \
  zsh-autosuggestions \
  zsh-history-substring-search \
  zsh-syntax-highlighting; do
  plugin_file="$HOME/.zsh/plugins/$plugin/$plugin.zsh"
  [[ -f "$plugin_file" ]] && source "$plugin_file"
done
unset plugin plugin_file

# Modern prompt and navigation.
command -v starship >/dev/null 2>&1 && eval "$(starship init zsh)"
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init zsh)"

# Fuzzy file and history search.
if command -v brew >/dev/null 2>&1; then
  fzf_prefix="$(brew --prefix fzf 2>/dev/null)"
  [[ -f "$fzf_prefix/shell/key-bindings.zsh" ]] && source "$fzf_prefix/shell/key-bindings.zsh"
  [[ -f "$fzf_prefix/shell/completion.zsh" ]] && source "$fzf_prefix/shell/completion.zsh"
  unset fzf_prefix
fi

# Useful modern command defaults. Use `command ls`, `command cat`, or
# `command find` for the original tools.
command -v eza >/dev/null 2>&1 && {
  alias ls='eza --icons --group-directories-first'
  alias ll='eza --icons --group-directories-first --long --git'
  alias la='eza --icons --group-directories-first --long --all --git'
}
command -v bat >/dev/null 2>&1 && alias cat='bat'
command -v fd >/dev/null 2>&1 && alias find='fd'

# Generated by envman when present.
[[ -s "$HOME/.config/envman/load.sh" ]] && source "$HOME/.config/envman/load.sh"

path=("$HOME/.local/bin" "$HOME/go/bin" $path)
export PATH
